# Generated by Django 5.2.4 on 2025-08-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('active', 'Active Plan'), ('saved', 'Saved Trip'), ('booked', 'Booked Trip')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(default='New Trip Plan', max_length=200),
        ),
    ]
