# Generated by Django 5.2.4 on 2025-07-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='attractions',
        ),
        migrations.AddField(
            model_name='carrental',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_rental_images/'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travel_agency_images/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='core.destination'),
        ),
    ]
