# Generated by Django 5.2.4 on 2025-08-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trip_end_date_trip_start_date_trip_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(default='My Ethiopian Adventure', max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('saved', 'Saved'), ('completed', 'Completed')], default='active', max_length=10),
        ),
    ]
