# Generated by Django 5.2.4 on 2025-08-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_trip_name_alter_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(default='New Trip Plan', max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('active', 'Active Plan'), ('saved', 'Saved Trip'), ('booked', 'Booked Trip')], default='active', max_length=10),
        ),
    ]
