# Generated by Django 5.2.4 on 2025-08-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_car_carrentalimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrental',
            name='price_per_day',
        ),
        migrations.AlterField(
            model_name='carrental',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_rental_images/', verbose_name='Cover Image'),
        ),
    ]
