# Generated by Django 5.2.4 on 2025-08-19 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_attraction_image_alter_destination_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelagency',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travel_agency_images/', verbose_name='Cover Image'),
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_images/')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='core.travelagency')),
            ],
        ),
        migrations.CreateModel(
            name='TravelAgencyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel_agency_gallery/')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.travelagency')),
            ],
        ),
        migrations.DeleteModel(
            name='DestinationImage',
        ),
    ]
