# Generated by Django 5.2.4 on 2025-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_travelagency_image_tourpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cars',
            field=models.ManyToManyField(blank=True, to='core.car'),
        ),
    ]
