# Generated by Django 5.2.4 on 2025-08-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_trip_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tour_packages',
            field=models.ManyToManyField(blank=True, to='core.tourpackage'),
        ),
    ]
