# Generated by Django 5.2.4 on 2025-09-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='services',
            field=models.TextField(blank=True, help_text='Comma-separated list of services offered.'),
        ),
    ]
