# Generated by Django 5.2.4 on 2025-09-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_accommodation_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='rating',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated list of detailed amenities.'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='location_description',
            field=models.TextField(blank=True, help_text='A short description of the location.'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation_images/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='services',
            field=models.TextField(blank=True, help_text='Comma-separated list of primary services for the main card.'),
        ),
        migrations.CreateModel(
            name='AccommodationGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodation_gallery/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_type_images/')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='core.accommodation')),
            ],
        ),
    ]
