# Generated by Django 5.2.4 on 2025-09-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_accommodation_price_per_night_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='core.roomtype'),
        ),
    ]
